### ISSUE TITLE
NFT: Refactor Claim

### ISSUE THREAD

**Issue by dappsar** [P4-Games/ChatterPay#55]
Refactor NFT Mint Items:

**ToDo**

- [x] Split code corresponding to section and page
- [x] Separate layout
- [x] Change app path from mint/id to nfts/mint/id
- [x] Add i18n to the section
- [x] Move network handles (URLs) to constants
- [x] Move API call to a Next.js endpoint
- [x] Testing
